FROM node:20-bookworm-slim AS build

ARG NEXT_PUBLIC_BACKEND_URL
ARG NEXT_PUBLIC_INVOICE_COMPANY_NAME
ARG NEXT_PUBLIC_INVOICE_COMPANY_DETAILS
ARG NEXT_PUBLIC_GUIDE_CHECKOUT_URL
ARG NEXT_PUBLIC_GUIDE_VIDEO_URL
ARG NEXT_PUBLIC_GUIDE_URL
ENV NEXT_PUBLIC_BACKEND_URL=${NEXT_PUBLIC_BACKEND_URL}
ENV NEXT_PUBLIC_INVOICE_COMPANY_NAME=${NEXT_PUBLIC_INVOICE_COMPANY_NAME}
ENV NEXT_PUBLIC_INVOICE_COMPANY_DETAILS=${NEXT_PUBLIC_INVOICE_COMPANY_DETAILS}
ENV NEXT_PUBLIC_GUIDE_CHECKOUT_URL=${NEXT_PUBLIC_GUIDE_CHECKOUT_URL}
ENV NEXT_PUBLIC_GUIDE_VIDEO_URL=${NEXT_PUBLIC_GUIDE_VIDEO_URL}
ENV NEXT_PUBLIC_GUIDE_URL=${NEXT_PUBLIC_GUIDE_URL}

WORKDIR /app/frontend

COPY frontend/package*.json ./
RUN npm ci

COPY frontend/ ./
RUN npm run build
RUN npm prune --omit=dev

FROM node:20-bookworm-slim AS runtime

ENV NODE_ENV=production
ENV PORT=4421
ENV HOSTNAME=0.0.0.0

WORKDIR /app/frontend

COPY --from=build /app/frontend/package*.json ./
COPY --from=build /app/frontend/node_modules ./node_modules
COPY --from=build /app/frontend/.next ./.next

EXPOSE 4421

CMD ["npm", "run", "start"]
